### ISSUE TITLE
Create repositories for rpi images

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/provider-k3s#26]
We need following docker image repositories for building the rpi based images

core-opensuse-arm-rpi-k3s
core-ubuntu-20-lts-arm-rpi-k3s
core-ubuntu-22-lts-arm-rpi-k3s
core-alpine-arm-rpi-k3s

**Comment by mauromorales** [comment]
Added them in quay: 

- https://quay.io/repository/kairos/core-opensuse-arm-rpi-k3s
- https://quay.io/repository/kairos/core-ubuntu-20-lts-arm-rpi-k3s
- https://quay.io/repository/kairos/core-ubuntu-22-lts-arm-rpi-k3s
- https://quay.io/repository/kairos/core-alpine-arm-rpi-k3s

Have a look and let me know if it's all good

**Comment by jimmykarily** [comment]
Closing as done. @venkatnsrinivasan please open again if something is not right.
